# Generated by Django 3.2 on 2024-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20240904_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('Gray', 'Серый'), ('Black', 'Чёрный'), ('White', 'Белый'), ('Gringer', 'Рыжий'), ('Mixed', 'Смешанный')], max_length=16),
        ),
    ]
